version: '3'
services:
  database:
    image: microsoft/mssql-server-linux:2017-latest
    container_name: eshop_db
    hostname: 'sqlserver'
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: P@ssw0rd
      MSSQL_PID: Developer
    ports:
      - "1433:1433"
    volumes:
      - ./database:/home/database
  #redis:
  #  image: "redis:alpine"
  #  container_name: eshop_redis
  #  ports:
  #    - "6379:6379"
  #rabbitmq:
  #  image: rabbitmq:3.7
  #  container_name: eshop_queue
  #  ports:
  #    - "5672:5672"
  api:
    container_name: eshop_web
    build: ./
    ports:
      - "8088:3000"
    depends_on:
      - database
      #- redis
      #- rabbitmq
    links:
      - database
      #- redis
      #- rabbitmq
    volumes:
      - ./:/home/app
    command: [ "npm", "start" ]